-- 1. Criação do Banco de Dados (Execute separado se necessário)
-- CREATE DATABASE intuitive_care_db;

-- Selecionar schema padrão (opcional, por padrão é o 'public')
SET search_path TO public;

-- =========================================================
-- 1. TABELA DIMENSIONAL: OPERADORAS (Dados Cadastrais)
-- =========================================================
DROP TABLE IF EXISTS tb_operadoras CASCADE;

CREATE TABLE tb_operadoras (
    registro_ans VARCHAR(20) NOT NULL PRIMARY KEY,
    cnpj VARCHAR(20),
    razao_social VARCHAR(255),
    nome_fantasia VARCHAR(255),
    modalidade VARCHAR(100),
    logradouro VARCHAR(255),
    numero VARCHAR(50),
    complemento VARCHAR(255),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf VARCHAR(2),
    cep VARCHAR(20),
    ddd VARCHAR(5),
    telefone VARCHAR(50),
    fax VARCHAR(50),
    endereco_eletronico VARCHAR(255),
    representante VARCHAR(255),
    cargo_representante VARCHAR(255),
    regiao_comercializacao VARCHAR(50),
    data_registro VARCHAR(20) 
);

-- Índices para performance
CREATE INDEX idx_operadoras_cnpj ON tb_operadoras(cnpj);
CREATE INDEX idx_operadoras_uf ON tb_operadoras(uf);

-- =========================================================
-- 2. TABELA DE FATOS: DESPESAS CONSOLIDADAS (Transacional)
-- =========================================================
DROP TABLE IF EXISTS tb_despesas_consolidadas CASCADE;

CREATE TABLE tb_consolidado_despesas (
    -- Em PG > 10, usamos IDENTITY em vez de SERIAL para auto-incremento padrão SQL
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    cnpj_operadora VARCHAR(18),
    razao_social VARCHAR(255), 
    trimestre VARCHAR(2),       -- Ex: '1T'
    ano INTEGER,
    valor_despesa NUMERIC(18,2), -- NUMERIC é sinônimo de DECIMAL no PG, alta precisão
    registro_ans VARCHAR(20),
    modalidade VARCHAR(100),
    uf CHAR(20)
    
    -- Opcional: Foreign Key (Constraint)
    -- CONSTRAINT fk_despesa_operadora FOREIGN KEY (registro_ans) REFERENCES tb_operadoras(registro_ans)
);

-- Índices para performance analítica (filtros por data e join)
CREATE INDEX idx_despesas_ano_trimestre ON tb_despesas_consolidadas(ano, trimestre);
CREATE INDEX idx_despesas_cnpj ON tb_despesas_consolidadas(cnpj_operadora);

-- =========================================================
-- 3. TABELA DE AGREGAÇÃO (Datamart / Resultado Analítico)
-- =========================================================
DROP TABLE IF EXISTS tb_despesas_agregadas CASCADE;

CREATE TABLE tb_despesas_agregadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(255),
    uf CHAR(2),
    total_despesas NUMERIC(18,2),
    media_trimestral NUMERIC(18,2),
    desvio_padrao NUMERIC(18,2)
);

-- Índice para ranking (Order By Total desc)
CREATE INDEX idx_agregadas_total ON tb_despesas_agregadas(total_despesas DESC);